/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author martin
 */
public class Rentas extends javax.swing.JFrame {

    /**
     * Creates new form Rentas
     */
    public Rentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cv_Lugar = new javax.swing.JTextField();
        cv_Turista = new javax.swing.JTextField();
        cv_Loker = new javax.swing.JTextField();
        cv_usuario = new javax.swing.JTextField();
        finicio = new javax.swing.JTextField();
        ffin = new javax.swing.JTextField();
        ing_renta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("CLAVE DE LUGAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 110, 116, 17);

        jLabel2.setText("CLAVE DE TURISTA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 127, 17);

        jLabel3.setText("CLAVE DE LOCKER ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 210, 130, 17);

        jLabel4.setText("CLAVE DE USUARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 260, 131, 17);

        jLabel5.setText("FECHA DE INICIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 310, 115, 17);

        jLabel6.setText("FECHA DE FIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 370, 95, 17);

        jLabel7.setText("INGRESO DE RENTA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 420, 133, 17);
        getContentPane().add(cv_Lugar);
        cv_Lugar.setBounds(200, 100, 300, 34);
        getContentPane().add(cv_Turista);
        cv_Turista.setBounds(200, 150, 300, 34);
        getContentPane().add(cv_Loker);
        cv_Loker.setBounds(200, 200, 300, 34);
        getContentPane().add(cv_usuario);
        cv_usuario.setBounds(200, 250, 300, 34);
        getContentPane().add(finicio);
        finicio.setBounds(200, 310, 300, 34);
        getContentPane().add(ffin);
        ffin.setBounds(200, 360, 300, 34);
        getContentPane().add(ing_renta);
        ing_renta.setBounds(200, 410, 300, 34);

        jLabel8.setText("INGRESE DATOS DE LA RENTA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 30, 297, 39);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 100, 90, 40);

        jButton2.setText("Ir al menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 160, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String cadena1, cadena2, cadena3, cadena4, cadena5, cadena6, cadena7;
        
        cadena1 = cv_Lugar.getText();
        cadena2 = cv_Turista.getText();
        cadena3 = cv_Loker.getText();
        cadena4 = cv_usuario.getText();
        cadena5 = finicio.getText();
        cadena6 = ffin.getText();
        cadena7 = ing_renta.getText();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cv_Loker;
    private javax.swing.JTextField cv_Lugar;
    private javax.swing.JTextField cv_Turista;
    private javax.swing.JTextField cv_usuario;
    private javax.swing.JTextField ffin;
    private javax.swing.JTextField finicio;
    private javax.swing.JTextField ing_renta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
