 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author martin
 */
public class Turistas extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    /**
     * Creates new form Turistas
     */
    public Turistas() {
        this.setTitle("Registro de Turistas");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Edad = new javax.swing.JTextField();
        txt_Nacionalidad = new javax.swing.JTextField();
        txt_Sexo = new javax.swing.JTextField();
        btn_guardas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("DATOS DEL TURISTA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 173, 39);

        jLabel2.setText("CLAVE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 31, 14);

        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 42, 14);

        jLabel4.setText("TELEFONO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 52, 14);

        jLabel5.setText("DIRECCION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 57, 14);

        jLabel6.setText("EDAD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 290, 27, 14);

        jLabel7.setText("NACIONALIDAD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 340, 77, 14);

        jLabel8.setText("SEXO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 390, 26, 14);
        getContentPane().add(txt_clave);
        txt_clave.setBounds(180, 80, 290, 20);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(180, 130, 290, 20);
        getContentPane().add(txt_telefono);
        txt_telefono.setBounds(180, 180, 290, 20);

        txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Direccion);
        txt_Direccion.setBounds(180, 230, 290, 20);
        getContentPane().add(txt_Edad);
        txt_Edad.setBounds(180, 280, 290, 20);
        getContentPane().add(txt_Nacionalidad);
        txt_Nacionalidad.setBounds(180, 330, 290, 20);
        getContentPane().add(txt_Sexo);
        txt_Sexo.setBounds(180, 380, 290, 20);

        btn_guardas.setText("Guardar");
        btn_guardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardas);
        btn_guardas.setBounds(520, 90, 90, 40);

        jButton2.setText("Ir al menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 150, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardasActionPerformed
    String cadena1, cadena2, cadena3, cadena4, cadena5, cadena6, cadena7,cadena8;
        
        cadena1 = txt_clave.getText();
        cadena2 = txt_nombre.getText();
        cadena3 = txt_telefono.getText();
        cadena4 = txt_Direccion.getText();
        cadena5 = txt_Edad.getText();
        cadena6 = txt_Nacionalidad.getText();
        cadena7 = txt_Sexo.getText();
        
         if (txt_clave.getText().equals("") || 
              (txt_nombre.getText().equals("") || 
              (txt_telefono.getText().equals("")) || 
              (txt_Direccion.getText().equals("")) || 
              (txt_Edad.getText().equals(""))|| 
              (txt_Nacionalidad.getText().equals(""))|| 
              (txt_Sexo.getText().equals("")))) 
             {
                javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                txt_nombre.requestFocus();
             
             }else{
                try {
           
            String url = "jdbc:mysql://localhost:3306/Lockers";
            String usuario = "root";
            String contraseña = "";
            
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); 
             conn = DriverManager.getConnection(url,usuario,contraseña); 
             //se crea un ciclo para que verificar y notifique su conexion
             if ( conn != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
                                       
                  stmt = conn.createStatement(); 
                  //Se inserta las cadenas en la tabla (Lugares)
                  stmt.executeUpdate("INSERT INTO Turistas VALUES('"+cadena1+"','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                   
       } catch (InstantiationException ex) {
           //se agrega de nuevo la tabla
           Logger.getLogger(Lugares.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(Lugares.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Lugares.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(Lugares.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (conn != null) {
                try {
                    conn.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        } 
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
         //Esto sirve para que despues de ingresar los datos se pongan vacios 
        this.txt_clave.setText("");
        this.txt_nombre.setText("");
        this.txt_telefono.setText("");
        this.txt_Direccion.setText("");
        this.txt_Edad.setText("");
        this.txt_Nacionalidad.setText("");
        this.txt_Sexo.setText("");
    }//GEN-LAST:event_btn_guardasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Nacionalidad;
    private javax.swing.JTextField txt_Sexo;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
